### ISSUE TITLE
Module support

### ISSUE THREAD

**Issue by thomasdigby** [filamentgroup/shoestring#100]
Do you have any plans to allow shoestring to be imported, either through require() or ES6 import?

**Comment by TehShrike** [comment]
Related: would you consider switching from AMD to ES6 imports and setting to allow modern bundlers to use [jsnext:main](https://github.com/rollup/rollup/wiki/jsnext:main) as an entry point, and eliminate unused code from making it to the final bundle?

**Comment by zachleat** [comment]
We actually only use modules as part of the build. I _just_ added a form of UMD as a stop-gap for now in #124

**Comment by jscinoz** [comment]
It seems that even when shoestring is imported as a module, it pollutes the global scope, setting window.shoestring and window.$. This breaks things when shoestring is used within a library that is in turn used in the context of a page that already includes jQuery (#129).

Looking at the bespoke UMD wrapper added in #124, the path for a non-module (i.e. browser) environment relies on the factory() function to assign globals as a side-effect, rather than assigning the return value of factory() itself. As a result, even in a module-supporting environment, the global scope is still polluted, leading to #129 and rendering shoestring unusable for many use-cases.

Fixing this should be fairly straight-forward, I'll send through a PR with a fix shortly.
