### ISSUE TITLE
throws errors causing existing JQuery apps to fail

### ISSUE THREAD

**Issue by jaichandra** [filamentgroup/shoestring#129]
JQuery handles a lot of errors silently and is helpful when creating mocks/demos

ex: 
`$(".combobox").combobox()` returns an empty array in jQuery
While the same when shoestring is included throws a `TypeError: $(...).combobox is not a function' error.

I understand that this should be handled in the application code, but I think it would be better if this stays as close as possible to JQuery or else `shoestring` should use a different namespace and not conflict with JQuery's `$`.

My usecase is Im using tablesaw in an app which already has jquery and Im now getting these errors which otherwise used to fail silently.

**Comment by zachleat** [comment]
Hm, @jaichandra sorry about the delayed response. If you have an app that includes jQuery, use the jQuery compatible version of tablesaw:
https://github.com/filamentgroup/tablesaw#user-content-the-full-tablesaw

`<script src="tablesaw.jquery.js"></script>` instead of `<script src="tablesaw.js"></script>`

I’m going to leave this issue open though, because I think it raises a good point.
