### ISSUE TITLE
Some IE8-specific code left in Shoestring 2.0?

### ISSUE THREAD

**Issue by steffenweber** [filamentgroup/shoestring#136]
Thank you for making a Shoestring release that gets rid of the IE8 workarounds!

I'm wondering whether there is more code that can be removed.

1. Is the `XMLHttpRequest` workaround using `ActiveXObject( "Microsoft.XMLHTTP" )` still necessary? IE9 supports `XMLHttpRequest`.

2. There are two occurences of a function `convertPropertyName` with comment "IE8 uses marginRight instead of margin-right". I guess they can be removed, too?

**Comment by zachleat** [comment]
Good catches! I’ve updated the code to reflect your first suggestion. However, on the second point the comment doesn’t quite indicate what the code is doing. `convertPropertyName` is also used for vendor prefix property names as well (think `webkitSpecificProperty` instead of `-webkit-specific-property`). I’ve removed the reference to IE8 there but the code is still useful.

Thank you—this was great!

**Comment by steffenweber** [comment]
Thank you! :smiley:
