### ISSUE TITLE
indexOf polyfill?

### ISSUE THREAD

**Issue by collinsethans** [filamentgroup/shoestring#85]
I notice the mention of IE8 browser but didn't find the polyfill for Array.prototype.indexOf, which I was looking for. MDN mentions this to be supported from IE9.

**Comment by JonathanPrince** [comment]
Try the .inArray() method, this should return the index if the element is found or -1 if not.

**Comment by johnbender** [comment]
```
shoestring master : grep -r indexOf src/
src/ajax/ajax.js:                       if( url.indexOf("?") >= 0 ){
src/ajax/ajax.js:                               if( req.status.toString().indexOf( "0" ) === 0 ){
src/shoestring.js:              if( pType === "string" && prim.indexOf( "<" ) === 0 ){
src/events/trigger.js:                                  if( ( "" + this[ evt ] ).indexOf( "function" ) > -1 ) {
shoestring master :
```

**Comment by JonathanPrince** [comment]
oops, i should of thought about that one before posting

**Comment by johnbender** [comment]
@JonathanPrince I think your response was the one @collinsethans was looking for though :+1: 

@collinsethans we probably won't add this feature if only because it seems easy to add a pollyfill externally for those that want too and we try to keep the size at a minimum where we can.

Thanks for the suggestion though, and if anyone else disagrees violently we can re-open.

**Comment by collinsethans** [comment]
Yes, of course externally we can add them. I just came across a very simple and optimized polyfill here: http://webreflection.blogspot.fr/2011/06/partial-polyfills.html
You may choose to add it if it fits, others benefit from it.
